# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='downVote',
            new_name='down_votes',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='upVote',
            new_name='up_votes',
        ),
    ]
