# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field
import imgag.models


class Migration(migrations.Migration):

    dependencies = [
        ('imgag', '0002_auto_20170225_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url_hash',
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, storage=imgag.models.OverwriteStorage(), upload_to='profile_images'),
        ),
    ]
