# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgag', '0004_auto_20170225_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='hash_id',
            new_name='hashid',
        ),
    ]
