# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import imgag.models


class Migration(migrations.Migration):

    dependencies = [
        ('imgag', '0005_auto_20170225_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uploaded_file',
            field=models.FileField(blank=True, storage=imgag.models.OverwriteStorage(), upload_to='uploads'),
        ),
    ]
